//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.GUI.FileServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FileServiceReference.ICacheFileService")]
    public interface ICacheFileService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICacheFileService/GetFileNames", ReplyAction="http://tempuri.org/ICacheFileService/GetFileNamesResponse")]
        string[] GetFileNames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICacheFileService/GetFileNames", ReplyAction="http://tempuri.org/ICacheFileService/GetFileNamesResponse")]
        System.Threading.Tasks.Task<string[]> GetFileNamesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICacheFileService/GetFile", ReplyAction="http://tempuri.org/ICacheFileService/GetFileResponse")]
        byte[] GetFile(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICacheFileService/GetFile", ReplyAction="http://tempuri.org/ICacheFileService/GetFileResponse")]
        System.Threading.Tasks.Task<byte[]> GetFileAsync(string path);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICacheFileServiceChannel : Client.GUI.FileServiceReference.ICacheFileService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CacheFileServiceClient : System.ServiceModel.ClientBase<Client.GUI.FileServiceReference.ICacheFileService>, Client.GUI.FileServiceReference.ICacheFileService {
        
        public CacheFileServiceClient() {
        }
        
        public CacheFileServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CacheFileServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CacheFileServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CacheFileServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] GetFileNames() {
            return base.Channel.GetFileNames();
        }
        
        public System.Threading.Tasks.Task<string[]> GetFileNamesAsync() {
            return base.Channel.GetFileNamesAsync();
        }
        
        public byte[] GetFile(string path) {
            return base.Channel.GetFile(path);
        }
        
        public System.Threading.Tasks.Task<byte[]> GetFileAsync(string path) {
            return base.Channel.GetFileAsync(path);
        }
    }
}
